import Footer from "@/components/footer";
import "./globals.css";
import Header from "@/components/header";
import CartProvider from "@/components/providers/CartProviders";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Tiệm hoa nàng thơm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body>
        <Toaster
          toastOptions={{
            style: {
              background: "rgb(51 65 85)",
              color: "#fff",
            },
          }}
        />
        <CartProvider>
          <Header />
          <div className="">{children}</div>        
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
